### ISSUE TITLE
FPL Ceiling bug

### ISSUE THREAD

**Issue by ZhangHuan0407** [qwertie/LoycCore#11]
FPL16 fixedPoint1 = FPL16.One;
Console.WriteLine(fixedPoint1.Ceiling()); // 2
double double1 = 1d;
Console.WriteLine(Math.Ceiling(double1)); // 1

I think the result of ceiling is incorrect, it should be 1, but the actual output is 2

**Comment by ZhangHuan0407** [comment]
I tried a few things and felt like it should be modified like this. I'm not 100% sure.

FPL16 test1 = FPL16.Prescaled((FPL16.One.N + 65535) & -65536);
Console.WriteLine(test1); // 1
FPL16 test2 = FPL16.Prescaled(((FPL16.One.N + 1) + 65535) & -65536);
Console.WriteLine(test2); // 2
FPL16 test3 = FPL16.Prescaled(((FPL16.One.N - 1) + 65535) & -65536);
Console.WriteLine(test3); // 1

// Decompile the code
public FPL16 Ceiling()
{
    return Prescaled((N & -65536) + 65536);
}
// Modified
public FPL16 Ceiling()
{
    return Prescaled((N + 65536 - 1) & -65536);
}

**Comment by qwertie** [comment]
Yeah, that result is clearly wrong, sorry! Thanks for bringing it to my attention. I assume you'd prefer to get a new version on NuGet?

**Comment by ZhangHuan0407** [comment]
thanks

**Comment by qwertie** [comment]
The fix is published to NuGet as v30.1.1.
